import {
  ShoppingCart, GraduationCap, HeartPulse, Landmark, Building2,
  Car, CalendarDays, Monitor, UtensilsCrossed, Plane, Dumbbell, Sparkles,
  TrendingUp, BarChart3, Clock, Star, ShieldCheck, Bell, Bot,
  Users, Zap, CheckCircle2, MessageCircle, ArrowRight,
  Package, CreditCard, RefreshCw, Megaphone, BookOpen,
  CalendarCheck, FileText, MapPin, Award, Repeat,
} from "lucide-react";
import type { ComponentType } from "react";
import type { LucideProps } from "lucide-react";

export interface Metric {
  value: string;
  label: string;
  icon: ComponentType<LucideProps>;
}

export interface UseCase {
  title: string;
  description: string;
  icon: ComponentType<LucideProps>;
  steps: string[];
}

export interface Industry {
  slug: string;
  label: string;
  icon: ComponentType<LucideProps>;
  color: string;
  heroTagline: string;
  heroSubtitle: string;
  challenge: string;
  solution: string;
  metrics: Metric[];
  useCases: UseCase[];
  quote: string;
  quoteAuthor: string;
  quoteRole: string;
  quoteCompany: string;
  relatedSlugs: string[];
}

export const INDUSTRY_LIST: Industry[] = [
  {
    slug: "ecommerce",
    label: "E-commerce",
    icon: ShoppingCart,
    color: "#15803d",
    heroTagline: "Turn every shopper into a loyal customer",
    heroSubtitle: "Online stores using bigbrosai see up to 38% cart recovery, 3× repeat purchases, and zero dependency on expensive ad retargeting — all from WhatsApp.",
    challenge: "The average e-commerce store loses 70% of potential revenue to abandoned carts, slow order communication, and customers who never come back after a single purchase. Email open rates sit at 22%, push notifications get ignored, and SMS feels impersonal. Meanwhile, your competitors are quietly winning customers back on WhatsApp.",
    solution: "bigbrosai connects directly to your store (Shopify, WooCommerce, or custom) and automates the entire customer lifecycle over WhatsApp — from the moment someone abandons a cart to post-delivery reviews and re-engagement campaigns. Every message is personalised, timely, and feels like it came from a human.",
    metrics: [
      { value: "38%", label: "Avg. Cart Recovery Rate", icon: TrendingUp },
      { value: "₹12L+", label: "Monthly Revenue Recovered", icon: BarChart3 },
      { value: "4.1×", label: "Repeat Purchase Rate", icon: RefreshCw },
      { value: "6 min", label: "Avg. Response Time", icon: Clock },
    ],
    useCases: [
      {
        title: "Abandoned Cart Recovery",
        icon: ShoppingCart,
        description: "When a customer leaves without buying, bigbrosai fires a personalised WhatsApp message within 15 minutes with a direct link back to their cart — and optionally a time-limited discount.",
        steps: [
          "Customer adds items to cart and exits without purchasing",
          "bigbrosai detects the abandonment via webhook in real-time",
          "A personalised WhatsApp message is sent within 15 minutes",
          "Message includes product image, cart total, and one-tap checkout link",
          "If no action in 2 hours, a second message with a 10% discount fires automatically",
          "If customer buys, the sequence stops. If not, a final nudge goes at 24 hours",
        ],
      },
      {
        title: "Order Confirmation & Tracking",
        icon: Package,
        description: "Replace boring email confirmations with rich WhatsApp updates — from order placed to out-for-delivery to delivered — keeping customers informed and support tickets low.",
        steps: [
          "Order is placed — instant WhatsApp confirmation sent with order details",
          "Order is packed — 'Your order is being prepared' message with ETA",
          "Order is shipped — tracking link shared with courier details",
          "Out for delivery — 'Arriving today between 2–6 PM' alert",
          "Delivered — confirmation message with review request and discount for next order",
        ],
      },
      {
        title: "Flash Sale Broadcasts",
        icon: Megaphone,
        description: "Segment your customer base and blast personalised sale alerts to the right audience at the right time — not a generic message to everyone.",
        steps: [
          "Segment customers by purchase history, location, or product category",
          "Create a WhatsApp broadcast with product images and offer details",
          "Schedule the blast 30 minutes before the sale goes live",
          "Include a one-tap 'Shop Now' link with UTM tracking",
          "Follow-up message 2 hours before sale ends for non-buyers",
          "Track open rates, clicks, and revenue attributed to the campaign",
        ],
      },
      {
        title: "COD Confirmation to Reduce Returns",
        icon: CreditCard,
        description: "Cash-on-delivery orders have a 40% return rate on average. A simple WhatsApp confirmation call-to-action before dispatch cuts this dramatically.",
        steps: [
          "COD order placed — WhatsApp message sent immediately",
          "Customer asked to confirm: 'Confirm' or 'Cancel' buttons shown",
          "If confirmed, order proceeds to dispatch normally",
          "If no response in 4 hours, a reminder is sent",
          "If cancelled, inventory is freed and the customer is offered an alternative",
          "Confirmed orders see 65% lower return rates on average",
        ],
      },
      {
        title: "Post-Purchase Upsell & Review",
        icon: Star,
        description: "After delivery, automatically ask for a review and recommend complementary products — turning one-time buyers into repeat customers.",
        steps: [
          "Delivery confirmed — 24-hour wait to let customer experience the product",
          "Review request sent with star-rating buttons directly in WhatsApp",
          "Positive reviewers receive a thank-you and a personalised upsell",
          "Negative reviewers are flagged for human follow-up immediately",
          "Upsell recommendation based on their purchase history via AI",
          "Repurchase reminder sent 30 days later for consumables",
        ],
      },
    ],
    quote: "We recovered ₹12 lakhs in the very first month. bigbrosai didn't just pay for itself — it changed how we think about customer communication entirely.",
    quoteAuthor: "Rohit Mehta",
    quoteRole: "Founder",
    quoteCompany: "StyleBazaar",
    relatedSlugs: ["food-delivery", "beauty-retail", "travel"],
  },
  {
    slug: "education",
    label: "Education",
    icon: GraduationCap,
    color: "#7c3aed",
    heroTagline: "Convert every enquiry into an enrolled student",
    heroSubtitle: "EdTech companies and institutes using bigbrosai see 4.2× higher lead conversion, 85% query resolution without human involvement, and 24/7 student support.",
    challenge: "Education businesses spend lakhs on Google and Meta ads to generate leads, but 60% of those leads go cold because follow-up is too slow or too generic. Students today expect instant, personalised responses — and if they don't get one, they enrol somewhere else within hours.",
    solution: "bigbrosai creates a fully automated WhatsApp admissions funnel that responds to every enquiry instantly, qualifies the lead, answers course-specific FAQs, shares brochures and fee structures, and schedules counselling calls — all without a single human touchpoint until the student is ready to enrol.",
    metrics: [
      { value: "4.2×", label: "Lead Conversion Rate", icon: TrendingUp },
      { value: "85%", label: "Query Auto-Resolution", icon: Bot },
      { value: "24/7", label: "Student Support Coverage", icon: Clock },
      { value: "60%", label: "Reduction in CAC", icon: BarChart3 },
    ],
    useCases: [
      {
        title: "Instant Lead Response & Qualification",
        icon: Bot,
        description: "The moment a student fills a form or clicks a WhatsApp ad, bigbrosai responds in under 60 seconds, qualifies their interest, and starts the admissions journey.",
        steps: [
          "Student submits an enquiry form or clicks a WhatsApp ad",
          "bigbrosai responds immediately with a personalised greeting",
          "AI chatbot asks qualification questions: course interest, location, budget",
          "Based on answers, student is shown relevant course options with brochure links",
          "Fee structure, batch timings, and faculty details shared automatically",
          "Counselling call scheduled directly in the chat with calendar integration",
        ],
      },
      {
        title: "7-Day Follow-up Nurture Sequence",
        icon: RefreshCw,
        description: "Most students don't enrol on the first contact. bigbrosai runs a 7-day automated sequence that keeps your institution top-of-mind.",
        steps: [
          "Day 1: Course brochure and success stories shared",
          "Day 2: 'Did you get a chance to review?' check-in",
          "Day 3: Video testimonial from a current student sent",
          "Day 5: Limited-seat or early-bird discount offer",
          "Day 7: Final nudge with counsellor's direct WhatsApp number",
          "Non-responders moved to a long-term drip sequence",
        ],
      },
      {
        title: "Fee Reminders & Payment Collection",
        icon: CreditCard,
        description: "Reduce fee defaulters and late payments with automated, friendly WhatsApp reminders that include direct payment links.",
        steps: [
          "Fee due date set in the system per student",
          "Reminder sent 7 days before due date",
          "Second reminder 3 days before with payment link",
          "Final reminder on due date",
          "Overdue notice on day 1 after due date with escalation option",
          "Payment confirmation and receipt sent automatically on payment",
        ],
      },
      {
        title: "Study Material & Schedule Delivery",
        icon: BookOpen,
        description: "Deliver class schedules, assignments, study materials, and important announcements directly on WhatsApp — where students actually are.",
        steps: [
          "Connect your LMS or Google Drive to bigbrosai",
          "New material uploaded triggers automatic WhatsApp notification",
          "Schedule changes push-notified immediately to affected batch",
          "Assignment deadlines sent 48 hours and 2 hours before due",
          "Students can reply to ask questions answered by AI or routed to teacher",
          "Attendance summary sent to parents weekly",
        ],
      },
      {
        title: "Result Alerts & Re-enrollment Campaigns",
        icon: Award,
        description: "Announce results personally and immediately, then convert successful students into the next level of your programme.",
        steps: [
          "Results uploaded — WhatsApp notification sent to each student individually",
          "Personalised message: congratulations or encouragement based on result",
          "Top performers offered advanced courses with special pricing",
          "All students offered next-level programme with limited-time enrolment offer",
          "Testimonial request sent to students who performed well",
          "Referral programme launched: 'Refer a friend, get ₹500 off'",
        ],
      },
    ],
    quote: "Our admissions team used to miss half the leads coming in after hours. Now the bot handles everything and we only step in to close high-intent prospects.",
    quoteAuthor: "Priya Nair",
    quoteRole: "Operations Head",
    quoteCompany: "LearnSpark",
    relatedSlugs: ["it-services", "events", "fitness"],
  },
  {
    slug: "healthcare",
    label: "Healthcare",
    icon: HeartPulse,
    color: "#dc2626",
    heroTagline: "Reduce no-shows, automate care — delight every patient",
    heroSubtitle: "Clinics and hospitals using bigbrosai cut no-shows by 67%, save 3+ staff hours daily, and achieve 4.9-star patient satisfaction scores.",
    challenge: "Healthcare providers lose 30% of appointment revenue to no-shows and last-minute cancellations. Staff waste hours on manual reminder calls. Patients forget post-discharge instructions. And critical health information buried in email inboxes never gets read.",
    solution: "bigbrosai creates a WhatsApp-first patient communication system — from appointment booking and smart reminders to lab report delivery and post-care follow-ups — reducing administrative burden and improving patient outcomes simultaneously.",
    metrics: [
      { value: "67%", label: "Reduction in No-shows", icon: TrendingUp },
      { value: "3 hrs", label: "Staff Time Saved Daily", icon: Clock },
      { value: "4.9★", label: "Patient Satisfaction Score", icon: Star },
      { value: "99%", label: "Message Delivery Rate", icon: ShieldCheck },
    ],
    useCases: [
      {
        title: "Smart Appointment Reminders",
        icon: CalendarCheck,
        description: "A sequence of WhatsApp reminders — 24 hours, 2 hours, and 30 minutes before — with one-tap confirm or reschedule buttons reduces no-shows dramatically.",
        steps: [
          "Appointment booked — confirmation sent immediately via WhatsApp",
          "24 hours before: reminder with doctor name, time, and 'Confirm / Reschedule' buttons",
          "2 hours before: final reminder with clinic location map link",
          "30 minutes before: 'We're ready for you' message",
          "No-show detected — automated follow-up to rebook within 24 hours",
          "All confirmations and cancellations sync back to your HMS",
        ],
      },
      {
        title: "Lab Report Delivery",
        icon: FileText,
        description: "Deliver lab reports securely over WhatsApp the moment they are ready — replacing missed calls and patient trips back to the clinic.",
        steps: [
          "Lab report generated in your LIS/HMS system",
          "bigbrosai sends a 'Your report is ready' WhatsApp notification",
          "Secure PDF report delivered directly in chat",
          "If values are outside normal range, a flag is added with doctor note",
          "Follow-up appointment booking option included in the same message",
          "Patient can ask questions about the report via the AI chatbot",
        ],
      },
      {
        title: "Post-Discharge Care Instructions",
        icon: BookOpen,
        description: "Patients forget 80% of verbal discharge instructions within an hour. bigbrosai delivers structured care plans on WhatsApp so patients can refer back anytime.",
        steps: [
          "Doctor finalises discharge summary in HMS",
          "bigbrosai sends personalised care instructions within 30 minutes",
          "Medication schedule with dosage times sent as a formatted message",
          "Follow-up appointment pre-booked and reminder set automatically",
          "Check-in message sent at day 3 and day 7 post-discharge",
          "Any red-flag symptoms reported by patient triggers immediate escalation",
        ],
      },
      {
        title: "Prescription Refill Reminders",
        icon: RefreshCw,
        description: "For chronic patients, bigbrosai tracks medication schedules and sends refill reminders before they run out — improving adherence and revenue.",
        steps: [
          "Prescription duration recorded at consultation",
          "5 days before medication runs out, a refill reminder is sent",
          "Patient can reply 'Refill' to trigger an order or appointment",
          "Pharmacy notified automatically if integrated",
          "Doctor notified if patient hasn't refilled in 10 days past due date",
          "Adherence summary shared with doctor for chronic condition management",
        ],
      },
      {
        title: "Health Camp & Vaccination Broadcasts",
        icon: Megaphone,
        description: "Run targeted awareness and prevention campaigns — from vaccination drives to free health check-up camps — reaching thousands of patients instantly.",
        steps: [
          "Segment patients by age, condition, or last visit date",
          "Personalised camp or vaccination drive invitation sent",
          "Registration link or 'Book a slot' button included",
          "Reminder sent 1 day before the camp",
          "Attendance confirmation and direction shared on the morning",
          "Post-camp follow-up with results and next steps",
        ],
      },
    ],
    quote: "Our no-show rate dropped from 32% to under 10% in two months. Patients now thank us for the reminders. It has genuinely improved care outcomes.",
    quoteAuthor: "Dr. Kavitha Rao",
    quoteRole: "Director",
    quoteCompany: "MedFirst Clinics",
    relatedSlugs: ["fitness", "beauty-retail", "events"],
  },
  {
    slug: "finance",
    label: "Finance & BFSI",
    icon: Landmark,
    color: "#0369a1",
    heroTagline: "Secure, compliant financial communication at scale",
    heroSubtitle: "Banks, NBFCs, and insurers using bigbrosai achieve 99.8% message delivery, 52% lift in loan applications, and zero compliance violations.",
    challenge: "Financial institutions need to communicate sensitive information — OTPs, transaction alerts, EMI reminders — with the highest levels of security and compliance. At the same time, they face intense competition for customer attention and loyalty, with customers increasingly ignoring email and SMS.",
    solution: "bigbrosai is an Official Meta Business Solution Provider (BSP), meaning every message is end-to-end encrypted, verified with a green tick, and delivered through a compliant channel. From KYC collection to EMI reminders to investment alerts, bigbrosai handles financial communication that customers trust.",
    metrics: [
      { value: "99.8%", label: "Message Delivery Rate", icon: ShieldCheck },
      { value: "52%", label: "Loan Application Uplift", icon: TrendingUp },
      { value: "0", label: "Compliance Violations", icon: CheckCircle2 },
      { value: "22%", label: "EMI Collection Improvement", icon: BarChart3 },
    ],
    useCases: [
      {
        title: "Transaction Alerts & OTP Delivery",
        icon: ShieldCheck,
        description: "Replace unreliable SMS OTPs with WhatsApp-delivered verification codes that customers trust — delivered from a verified business number.",
        steps: [
          "Customer initiates a transaction or login",
          "OTP generated in your core banking/fintech system",
          "Secure WhatsApp message sent from verified green-tick number",
          "Message explicitly states: 'Do not share this OTP with anyone'",
          "Delivery confirmation received in under 3 seconds",
          "All OTP messages logged for compliance audit trail",
        ],
      },
      {
        title: "EMI Reminders & Collection",
        icon: CreditCard,
        description: "Automated EMI reminders with payment links reduce defaults and eliminate the need for expensive outbound calling teams.",
        steps: [
          "EMI schedule loaded from your loan management system",
          "10-day advance reminder sent: 'Your EMI of ₹X is due on DD/MM'",
          "3-day reminder with direct payment link",
          "Due-date reminder at 9 AM",
          "Overdue notice at 9 AM next day with escalation option",
          "Payment confirmed — receipt WhatsApp'd automatically",
        ],
      },
      {
        title: "KYC Document Collection",
        icon: FileText,
        description: "Collect KYC documents via WhatsApp — customers simply photograph and send their documents without visiting a branch.",
        steps: [
          "Customer onboarding initiated — WhatsApp KYC flow triggered",
          "List of required documents sent with clear instructions",
          "Customer sends photo of each document via WhatsApp",
          "AI validates document quality and type automatically",
          "Documents uploaded to your KYC system with metadata",
          "Completion confirmation and next steps sent to customer",
        ],
      },
      {
        title: "Insurance Renewal Campaigns",
        icon: RefreshCw,
        description: "Proactive, personalised renewal reminders dramatically reduce policy lapses and churn, with one-tap renewal and premium payment options.",
        steps: [
          "Policy expiry dates synced from your insurance management system",
          "60-day advance notice: benefits summary and renewal link",
          "30-day reminder with comparative premium options",
          "7-day urgent reminder with special no-cost renewal offer",
          "Expiry day: final alert with phone support option",
          "Lapsed policy: win-back campaign with re-onboarding incentive",
        ],
      },
      {
        title: "Investment Portfolio Alerts",
        icon: BarChart3,
        description: "Proactively inform customers about portfolio performance, new fund opportunities, and important market events — building trust and increasing AUM.",
        steps: [
          "Portfolio performance report generated (weekly/monthly)",
          "Personalised WhatsApp summary sent with key gains/losses",
          "New fund recommendation based on customer's risk profile",
          "Market event alerts (budget, rate change) with impact on their portfolio",
          "SIP due reminders with payment link",
          "Tax-saving investment reminders before March 31",
        ],
      },
    ],
    quote: "bigbrosai gave us a fully compliant WhatsApp channel. Our EMI collection rate improved by 22% and customer complaints about missed payments dropped to near zero.",
    quoteAuthor: "Anil Sharma",
    quoteRole: "CTO",
    quoteCompany: "FinEdge NBFC",
    relatedSlugs: ["real-estate", "it-services", "ecommerce"],
  },
  {
    slug: "real-estate",
    label: "Real Estate",
    icon: Building2,
    color: "#d97706",
    heroTagline: "Qualify buyers faster and close deals sooner",
    heroSubtitle: "Real estate teams using bigbrosai see 3× faster lead qualification, 41% site visit conversion, and ₹2.8 Cr+ in monthly pipeline generated.",
    challenge: "Real estate leads have a very short window of interest — 80% of them go cold within 48 hours of enquiring. Agents waste hours calling unqualified leads, manually sending brochures, and following up with prospects who have already bought from a competitor.",
    solution: "bigbrosai's AI chatbot qualifies every lead instantly on WhatsApp, shares property brochures and virtual tour links, answers location and pricing FAQs, and books site visits — so your sales team only picks up the phone for warm, ready-to-visit prospects.",
    metrics: [
      { value: "3×", label: "Faster Lead Qualification", icon: Zap },
      { value: "41%", label: "Site Visit Conversion Rate", icon: TrendingUp },
      { value: "₹2.8Cr", label: "Pipeline Generated Monthly", icon: BarChart3 },
      { value: "80%", label: "Reduction in Cold Calls", icon: Clock },
    ],
    useCases: [
      {
        title: "AI-Powered Lead Qualification",
        icon: Bot,
        description: "Every new enquiry is instantly engaged by bigbrosai's AI chatbot that qualifies budget, location preference, BHK requirement, and timeline — before any human gets involved.",
        steps: [
          "Lead submits form or clicks WhatsApp ad",
          "AI chatbot greets and asks: 'What type of property are you looking for?'",
          "Qualification questions: budget range, preferred location, BHK, possession timeline",
          "Based on answers, matching properties shortlisted and shared",
          "Virtual tour links and floor plans sent automatically",
          "Hot leads (budget + timeline match) flagged and routed to senior sales team",
        ],
      },
      {
        title: "Property Brochure & Virtual Tour Sharing",
        icon: FileText,
        description: "Share rich property details — brochures, floor plans, location maps, and virtual tour links — on WhatsApp the moment a prospect shows interest.",
        steps: [
          "Lead expresses interest in a project or configuration",
          "Project brochure PDF shared immediately in chat",
          "Floor plans for relevant BHK sent as images",
          "Google Maps location pin shared with directions",
          "Virtual 3D tour link shared with a compelling preview",
          "Amenities video and master plan shared on follow-up",
        ],
      },
      {
        title: "Site Visit Scheduling & Reminders",
        icon: MapPin,
        description: "Convert interest into action — bigbrosai books site visits, confirms times, and sends reminder sequences that dramatically increase actual show rates.",
        steps: [
          "Prospect expresses interest in visiting — available slots shown",
          "Slot selected in chat — confirmation sent immediately",
          "Day-before reminder with site address and sales rep contact",
          "Morning of visit: 'See you at 11 AM' message with directions",
          "Post-visit: personalised follow-up within 4 hours",
          "No-show: rescheduling offer sent within 24 hours",
        ],
      },
      {
        title: "Post-Visit Nurture & Documentation",
        icon: FileText,
        description: "After a site visit, bigbrosai continues to nurture the prospect with payment plans, legal documentation FAQs, and financing options.",
        steps: [
          "Post-visit message: 'Hope you loved the property! Any questions?'",
          "Payment plan options shared as a formatted message",
          "Home loan eligibility calculator link provided",
          "Bank tie-up details and pre-approved loan offers shared",
          "Any objections handled by AI or escalated to human",
          "Booking form and token amount payment link sent when ready",
        ],
      },
      {
        title: "Project Launch Campaigns",
        icon: Megaphone,
        description: "Launch new projects to your entire database of interested prospects with personalised WhatsApp campaigns that generate a flood of site visit bookings.",
        steps: [
          "Segment database by previously expressed BHK and budget preferences",
          "Pre-launch teaser sent 7 days before: 'Something exciting is coming'",
          "Launch day: full project details blast with early-bird pricing",
          "Limited inventory message creates urgency: 'Only 12 units left at this price'",
          "Interested responses automatically routed to sales team",
          "Post-launch follow-up for non-responders at day 3 and day 7",
        ],
      },
    ],
    quote: "We went from 5 site visits a week to 23. The AI qualifies everyone and books the visit. My team just shows up and closes. It is genuinely incredible.",
    quoteAuthor: "Suresh Patel",
    quoteRole: "Sales Director",
    quoteCompany: "NestVista Realty",
    relatedSlugs: ["finance", "ecommerce", "automobile"],
  },
  {
    slug: "automobile",
    label: "Automobile",
    icon: Car,
    color: "#64748b",
    heroTagline: "More test drives. More service bookings. More loyal customers.",
    heroSubtitle: "Auto dealerships using bigbrosai see 2.7× more test drive bookings, 78% service reminder open rates, and 60% higher repeat service customers.",
    challenge: "Car dealerships miss 40% of after-hours enquiries while competitors respond instantly. Service centres lose repeat business because customers simply forget when their next service is due. And new model launches fail to excite existing customers who never see the communication.",
    solution: "bigbrosai creates a 24/7 WhatsApp showroom — qualifying test drive enquiries, booking service appointments, sending personalised EMI alerts, and keeping your entire customer base warm for every new launch.",
    metrics: [
      { value: "2.7×", label: "Test Drive Bookings", icon: TrendingUp },
      { value: "78%", label: "Service Reminder Open Rate", icon: Bell },
      { value: "60%", label: "Repeat Service Rate Increase", icon: Repeat },
      { value: "40%", label: "After-hours Enquiries Captured", icon: Clock },
    ],
    useCases: [
      {
        title: "Test Drive Booking & Qualification",
        icon: CalendarCheck,
        description: "bigbrosai responds to every test drive enquiry — day or night — qualifies the prospect, and books a slot without involving your sales team.",
        steps: [
          "Customer enquires via WhatsApp, website, or social media ad",
          "AI chatbot responds immediately with available models",
          "Budget, fuel preference, and usage questions asked to qualify",
          "Test drive slot options shown — customer selects directly in chat",
          "Confirmation sent with showroom address and sales rep contact",
          "Day-before reminder with directions and parking instructions",
        ],
      },
      {
        title: "Service Due Reminders",
        icon: Bell,
        description: "Automatically remind customers when their next service is due based on last service date — before they start ignoring the dashboard warning light.",
        steps: [
          "Last service date and vehicle details stored after each visit",
          "3,000 km or 3-month reminder calculated automatically",
          "WhatsApp reminder sent: 'Your [Model] service is due on [Date]'",
          "One-tap service booking option included",
          "Preferred service advisor can be requested in chat",
          "Reminder escalation at 2 weeks overdue",
        ],
      },
      {
        title: "Insurance & EMI Alerts",
        icon: CreditCard,
        description: "Help customers never miss an EMI or let their insurance lapse — building trust while protecting your dealership's finance portfolio.",
        steps: [
          "Finance and insurance records loaded from your DMS",
          "EMI reminder sent 5 days before due date with payment link",
          "Insurance expiry reminder 60 days and 30 days before",
          "Renewal quote shared with preferred insurer options",
          "Late EMI escalation with finance manager contact",
          "Successful payment confirmation sent automatically",
        ],
      },
      {
        title: "New Model Launch Campaigns",
        icon: Megaphone,
        description: "Turn your existing customer database into an excited launch audience — segmented by their current vehicle and preferences.",
        steps: [
          "Segment customers by current vehicle age, model, and budget",
          "Teaser campaign launched 2 weeks before model reveal",
          "Launch day: full model details, colours, and pricing sent",
          "Exclusive test drive pre-booking for existing customers",
          "Trade-in evaluation offer sent with link to book appointment",
          "Finance scheme details shared for interested prospects",
        ],
      },
      {
        title: "Roadside Assistance & Complaint Tracking",
        icon: ShieldCheck,
        description: "Be there for your customers in their most stressful moments — a WhatsApp SOS system builds lifetime loyalty that no competitor can match.",
        steps: [
          "Customer sends 'Help' or clicks SOS button on website",
          "AI collects location, issue type, and vehicle registration",
          "Nearest service van or towing team notified immediately",
          "Customer sent ETA and technician contact",
          "Progress updates sent every 30 minutes via WhatsApp",
          "Post-service feedback collected and escalated if negative",
        ],
      },
    ],
    quote: "Our service bay is now fully booked 3 weeks in advance. bigbrosai's reminders bring customers in before they even realise their service is overdue.",
    quoteAuthor: "Manish Gupta",
    quoteRole: "General Manager",
    quoteCompany: "AutoElite Motors",
    relatedSlugs: ["finance", "real-estate", "ecommerce"],
  },
  {
    slug: "events",
    label: "Events",
    icon: CalendarDays,
    color: "#db2777",
    heroTagline: "Fill every seat. Keep every attendee engaged.",
    heroSubtitle: "Event organisers using bigbrosai see 89% attendee show rates, 5× registration conversions, and average registration time of under 2 minutes.",
    challenge: "Event organisers spend months planning and marketing, only to see 35% of confirmed registrations drop off at the last minute. Attendees miss crucial logistics information buried in emails, and post-event engagement falls off a cliff — making each event feel like starting from scratch.",
    solution: "bigbrosai manages the entire event communication lifecycle on WhatsApp — from registration to real-time updates on the day to post-event re-engagement — creating experiences so seamless that attendees become regulars.",
    metrics: [
      { value: "89%", label: "Attendee Show Rate", icon: Users },
      { value: "5×", label: "Registration Conversion Rate", icon: TrendingUp },
      { value: "2 min", label: "Average Registration Time", icon: Clock },
      { value: "4.7★", label: "Attendee Satisfaction Score", icon: Star },
    ],
    useCases: [
      {
        title: "WhatsApp Registration Flow",
        icon: CalendarCheck,
        description: "Replace complex registration forms with a conversational WhatsApp flow — attendees register in under 2 minutes without leaving the app.",
        steps: [
          "Interested person clicks WhatsApp link from social, email, or ad",
          "AI chatbot greets and presents event overview",
          "Name, email, ticket type, and dietary preferences collected conversationally",
          "Payment link sent directly in chat for paid events",
          "Registration confirmation with QR code ticket sent instantly",
          "Added to event broadcast group for future updates",
        ],
      },
      {
        title: "Countdown Reminder Sequence",
        icon: Bell,
        description: "A carefully timed sequence of reminders — 7 days, 24 hours, and 2 hours before — with venue details and schedule keeps no-shows to a minimum.",
        steps: [
          "7 days before: 'We can't wait to see you' with agenda teaser",
          "3 days before: Speaker and session highlights shared",
          "24 hours before: Full schedule, dress code, and venue map",
          "2 hours before: 'See you soon' with parking and entrance details",
          "Event morning: Live updates on any schedule changes",
          "On arrival: Check-in instructions via WhatsApp",
        ],
      },
      {
        title: "Live Event Communication",
        icon: Megaphone,
        description: "Keep attendees informed and engaged in real-time on the day — schedule changes, session links, networking breaks, and more.",
        steps: [
          "Session start notifications: 'Track A is about to begin in Hall 2'",
          "Speaker bio shared just before each session",
          "Q&A submissions collected via WhatsApp during sessions",
          "Networking break matchmaking: who else to meet based on interests",
          "Emergency announcements reach all attendees in under 30 seconds",
          "Session feedback collected immediately after each talk",
        ],
      },
      {
        title: "Feedback & Review Collection",
        icon: Star,
        description: "Post-event feedback collected via WhatsApp gets 5× higher response rates than post-event email surveys — giving you the insights to improve.",
        steps: [
          "2 hours after event ends: 'How was your experience?' message sent",
          "Quick star-rating buttons for each session attended",
          "Open text field for detailed feedback",
          "Positive respondents asked to leave a Google or LinkedIn review",
          "Negative feedback flagged for immediate follow-up",
          "Aggregated insights dashboard available in bigbrosai",
        ],
      },
      {
        title: "Next Event Promotion & Loyalty",
        icon: Repeat,
        description: "Previous attendees are your best audience for future events. bigbrosai automatically nurtures them into loyal repeat attendees.",
        steps: [
          "2 weeks post-event: highlights reel or key takeaways shared",
          "Exclusive early-bird access offered to previous attendees",
          "Referral campaign: 'Bring a colleague, both save 20%'",
          "VIP community WhatsApp group created for loyal attendees",
          "Next event teaser shared 3 months out",
          "Anniversary message: 'It's been a year since [Event Name]!'",
        ],
      },
    ],
    quote: "Our last conference had a 92% show rate — unheard of in our industry. bigbrosai kept every attendee informed, excited, and connected throughout.",
    quoteAuthor: "Neha Joshi",
    quoteRole: "Event Director",
    quoteCompany: "SummitHQ",
    relatedSlugs: ["education", "beauty-retail", "fitness"],
  },
  {
    slug: "it-services",
    label: "IT Services",
    icon: Monitor,
    color: "#0891b2",
    heroTagline: "Accelerate your sales cycle with 24/7 intelligent engagement",
    heroSubtitle: "SaaS and IT companies using bigbrosai see 48% demo conversion rates, 24/7 lead qualification, and 3-day faster average sales cycles.",
    challenge: "SaaS and IT companies spend heavily on content and SEO to attract prospects, but lose most of them because responses are too slow. A prospect evaluating 5 solutions simultaneously will choose the first one to provide a helpful, instant response.",
    solution: "bigbrosai deploys an intelligent WhatsApp bot on your website and landing pages that instantly answers technical questions, shares case studies, books demos, and nurtures prospects through a personalised sequence — keeping your brand at the top of every evaluation.",
    metrics: [
      { value: "48%", label: "Demo Conversion Rate", icon: TrendingUp },
      { value: "24/7", label: "Lead Qualification Coverage", icon: Bot },
      { value: "3 days", label: "Faster Average Sales Cycle", icon: Clock },
      { value: "3.2×", label: "Trial-to-Paid Conversion", icon: BarChart3 },
    ],
    useCases: [
      {
        title: "Instant Product Enquiry Handling",
        icon: Bot,
        description: "Every prospect gets an intelligent, instant response to their technical questions — even at midnight — keeping your sales pipeline warm around the clock.",
        steps: [
          "Prospect visits website and clicks 'Chat with us on WhatsApp'",
          "AI bot greets and asks: 'What are you looking to solve?'",
          "Use case identified and relevant features highlighted",
          "Case studies from the same industry shared automatically",
          "Pricing page or custom pricing form offered based on company size",
          "All conversation data synced to your CRM (HubSpot, Salesforce)",
        ],
      },
      {
        title: "Demo Scheduling & Preparation",
        icon: CalendarCheck,
        description: "Convert 'I'm interested' into a confirmed demo slot in under 60 seconds — with automatic preparation materials sent to the prospect.",
        steps: [
          "Prospect expresses interest in a demo",
          "Available slots shown from your calendar (Calendly/Google integration)",
          "Prospect selects slot — confirmation sent immediately",
          "Pre-demo questionnaire sent 24 hours before",
          "Demo day reminder with meeting link",
          "Post-demo follow-up with recording and next steps within 4 hours",
        ],
      },
      {
        title: "Trial Onboarding & Activation",
        icon: Zap,
        description: "Turn free trial sign-ups into activated users with a guided WhatsApp onboarding sequence that gets them to their 'aha moment' faster.",
        steps: [
          "Trial signup triggers immediate WhatsApp welcome message",
          "Day 1: Quick-start guide and first task to complete",
          "Day 3: Check-in — 'Have you tried [key feature] yet?'",
          "Day 5: Use case video most relevant to their industry",
          "Day 10: 'Your trial has 4 days left' with upgrade prompt",
          "Day 14: Personal outreach from sales rep for high-engagement trials",
        ],
      },
      {
        title: "Renewal & Upsell Campaigns",
        icon: RefreshCw,
        description: "Prevent churn and expand accounts with proactive renewal communication and contextual upsell campaigns delivered on WhatsApp.",
        steps: [
          "60 days before renewal: health check and success metrics shared",
          "30 days before: renewal proposal with multi-year discount",
          "Usage spike detected: 'You're hitting limits — upgrade to avoid disruption'",
          "New feature announcement targeted to relevant account segments",
          "Churned customer win-back campaign at 30 and 90 days",
          "NPS survey sent via WhatsApp with high response rates",
        ],
      },
      {
        title: "Support Ticket Deflection",
        icon: ShieldCheck,
        description: "Deflect up to 70% of support tickets with AI-powered WhatsApp support that resolves common issues instantly without involving your team.",
        steps: [
          "Customer sends support query via WhatsApp",
          "AI identifies issue type and searches knowledge base",
          "Step-by-step resolution guide sent with screenshots",
          "If unresolved, ticket created and assigned with estimated resolution time",
          "Resolution update sent via WhatsApp when ticket is closed",
          "CSAT survey sent 30 minutes after resolution",
        ],
      },
    ],
    quote: "Our SDRs now spend 80% of their time on qualified, demo-ready prospects. Everything before that — qualification, nurturing, scheduling — the bot handles perfectly.",
    quoteAuthor: "Vikram Iyer",
    quoteRole: "VP Sales",
    quoteCompany: "CloudNine Software",
    relatedSlugs: ["education", "finance", "ecommerce"],
  },
  {
    slug: "food-delivery",
    label: "Food & Delivery",
    icon: UtensilsCrossed,
    color: "#ea580c",
    heroTagline: "Own your customer relationship. Keep every rupee of margin.",
    heroSubtitle: "Restaurants and cloud kitchens using bigbrosai achieve 44% repeat order rates, ₹0 platform commission on direct orders, and 4.8-star customer satisfaction.",
    challenge: "Restaurants pay 25–35% commission to food delivery platforms on every order — and worse, they don't own the customer relationship. One algorithm change and your restaurant disappears. Meanwhile, loyal customers who love your food have no direct way to order from you.",
    solution: "bigbrosai builds a direct WhatsApp ordering channel — your own menu, your own promotions, your own customer database. Customers order directly from you, you keep 100% of the margin, and every order builds your customer relationship rather than a platform's.",
    metrics: [
      { value: "44%", label: "Repeat Order Rate", icon: Repeat },
      { value: "28%", label: "Average Margin (vs 8% on apps)", icon: BarChart3 },
      { value: "4.8★", label: "Customer Satisfaction Score", icon: Star },
      { value: "30%", label: "Orders Shifted to Direct Channel", icon: TrendingUp },
    ],
    useCases: [
      {
        title: "Direct WhatsApp Ordering",
        icon: ShoppingCart,
        description: "A conversational menu on WhatsApp lets customers browse, customise, and order in under 3 minutes — with no app download and no platform commission.",
        steps: [
          "Customer clicks your WhatsApp link from Instagram, Google, or receipt QR",
          "AI chatbot presents menu categories with images and prices",
          "Customer selects items, customises (spice level, add-ons, etc.)",
          "Order summary shown with total and delivery charge",
          "Payment link sent (UPI, card, or COD option)",
          "Order confirmation and estimated delivery time sent automatically",
        ],
      },
      {
        title: "Real-time Order & Delivery Tracking",
        icon: Package,
        description: "Keep customers informed at every step — order accepted, being prepared, picked up, and out for delivery — reducing support calls to near zero.",
        steps: [
          "Order accepted: 'Your order is confirmed! Preparation time: 20 mins'",
          "Being prepared: 'Chef is working on your order'",
          "Picked up: rider name and contact number shared",
          "On the way: live tracking link shared",
          "Nearby: '5 minutes away!'",
          "Delivered: confirmation message with feedback request",
        ],
      },
      {
        title: "Loyalty Points & Reward Redemption",
        icon: Award,
        description: "Build a simple but powerful loyalty programme entirely on WhatsApp — no app, no card, just messages and points that drive repeat orders.",
        steps: [
          "Every order earns points based on order value",
          "Points balance shared with every order confirmation",
          "Monthly summary: 'You have 340 points — that's a free biryani!'",
          "Redemption request handled in chat: 'Redeem 200 points for ₹50 off'",
          "Birthday and anniversary bonus points sent automatically",
          "Referral programme: 'Share your link, earn 100 points per referral'",
        ],
      },
      {
        title: "Daily Specials & Combo Deals",
        icon: Megaphone,
        description: "Push daily special notifications to your WhatsApp subscriber list — the restaurant equivalent of a flash sale with near-100% visibility.",
        steps: [
          "Chef decides today's special at 10 AM",
          "Photo + description broadcast sent to all subscribers at 11 AM",
          "Limited quantity creates natural urgency",
          "Combo deal offer: 'Order before 1 PM, get a free dessert'",
          "Dinner special reminder at 5 PM for non-lunch-orderers",
          "Weekend special campaign: Friday teaser, Saturday reveal",
        ],
      },
      {
        title: "Review & Reputation Management",
        icon: Star,
        description: "Collect reviews at the perfect moment — right after a positive delivery experience — and build your Google and Zomato ratings systematically.",
        steps: [
          "30 minutes after delivery: 'How was your meal?' WhatsApp message",
          "Quick rating buttons: ⭐⭐⭐⭐⭐",
          "4-5 star raters: asked to share on Google/Zomato with a direct link",
          "1-3 star raters: personal apology and a discount for next order",
          "Consistent review collection builds platform ratings organically",
          "Negative feedback flagged for immediate kitchen/delivery review",
        ],
      },
    ],
    quote: "We moved 30% of our orders off Swiggy to direct WhatsApp orders in 3 months. Our margins went from 8% to 28%. bigbrosai literally saved our business.",
    quoteAuthor: "Anjali Desai",
    quoteRole: "Founder",
    quoteCompany: "Tiffin Express",
    relatedSlugs: ["ecommerce", "beauty-retail", "events"],
  },
  {
    slug: "travel",
    label: "Travel",
    icon: Plane,
    color: "#2563eb",
    heroTagline: "Personalise every journey from enquiry to homecoming",
    heroSubtitle: "Travel agencies using bigbrosai see 3.8× enquiry-to-booking conversion, 18-minute average quote response time, and 92% document delivery success.",
    challenge: "Travel agencies lose 55% of enquiries to OTAs and competitors because they can't respond fast enough with personalised itineraries. Travellers filling forms on 5 different websites will book with whoever provides the best experience fastest — and that's usually not a local agent.",
    solution: "bigbrosai enables travel agencies to deliver instant, personalised quotes, share rich itineraries, collect documents, and provide real-time travel alerts — all on WhatsApp — giving boutique agencies the responsiveness of an OTA with the personalisation they can't match.",
    metrics: [
      { value: "3.8×", label: "Enquiry-to-Booking Conversion", icon: TrendingUp },
      { value: "18 min", label: "Average Quote Response Time", icon: Clock },
      { value: "92%", label: "Document Delivery Success Rate", icon: CheckCircle2 },
      { value: "65%", label: "Repeat Booking Rate", icon: Repeat },
    ],
    useCases: [
      {
        title: "Instant Quote & Itinerary Delivery",
        icon: FileText,
        description: "Respond to every travel enquiry with a personalised itinerary within minutes — not hours — beating OTAs at their own game.",
        steps: [
          "Customer enquires about a destination via WhatsApp",
          "AI chatbot collects: dates, travellers, budget, interests, accommodation preference",
          "Matching packages fetched from your catalogue and sent as a rich message",
          "Day-wise itinerary PDF shared instantly with hotel and activity details",
          "Price breakdown sent with inclusions and exclusions clearly listed",
          "Payment options: full payment link or instalment plan shown",
        ],
      },
      {
        title: "Visa & Document Collection",
        icon: FileText,
        description: "Collect visa documents, passport copies, and travel insurance forms via WhatsApp — with automated validation and status tracking.",
        steps: [
          "Booking confirmed — document checklist sent via WhatsApp",
          "Customer uploads documents one by one in chat",
          "AI validates document type and quality",
          "Missing or invalid document flagged with clear instructions",
          "Submission confirmation sent with visa application timeline",
          "Visa status updates sent automatically as they arrive",
        ],
      },
      {
        title: "Pre-Trip Countdown & Preparation",
        icon: Bell,
        description: "A sequenced pre-trip communication plan ensures travellers are prepared, excited, and less likely to cancel.",
        steps: [
          "30 days before: destination guide and weather advisory",
          "14 days before: packing checklist based on destination and season",
          "7 days before: confirmed hotel vouchers and activity bookings shared",
          "3 days before: check-in reminders and airline seat selection links",
          "Day before: final itinerary, emergency contacts, and travel tips",
          "Day of travel: check-in time reminder and transfer confirmation",
        ],
      },
      {
        title: "Real-time Travel Alerts",
        icon: Bell,
        description: "Be the travel companion that proactively alerts travellers to flight delays, gate changes, and destination advisories — building trust that generates referrals.",
        steps: [
          "Flight details synced via API",
          "Delay detected: immediate WhatsApp notification with new departure time",
          "Gate change: push notification with new gate location",
          "Weather advisory at destination: helpful tips shared",
          "Emergency contact number shared with embassy details",
          "Travel insurance claim process shared if needed",
        ],
      },
      {
        title: "Post-Trip Review & Re-booking",
        icon: Repeat,
        description: "Convert every happy traveller into a loyal repeat customer and referral source with perfectly timed post-trip communication.",
        steps: [
          "48 hours after return: 'Hope you had an amazing trip!' message",
          "Feedback survey with star rating for each component",
          "Photo sharing invitation: 'Share your favourite moment!'",
          "Review request: TripAdvisor / Google link for 4-5 star responses",
          "Anniversary message: 'A year ago, you were in Bali...'",
          "Next trip suggestion based on their travel history and season",
        ],
      },
    ],
    quote: "We now respond to every enquiry with a personalised itinerary in under 20 minutes. Our conversion rate has nearly quadrupled and we've stopped losing business to OTAs.",
    quoteAuthor: "Rajan Bose",
    quoteRole: "CEO",
    quoteCompany: "Wanderlust Holidays",
    relatedSlugs: ["events", "ecommerce", "food-delivery"],
  },
  {
    slug: "fitness",
    label: "Fitness",
    icon: Dumbbell,
    color: "#16a34a",
    heroTagline: "Reduce churn, fill classes, build a thriving fitness community",
    heroSubtitle: "Gyms and fitness studios using bigbrosai see 55% less member churn, 82% class attendance rates, and 2.1× higher membership renewals.",
    challenge: "Fitness studios see 40% member churn in the first 3 months. Members join with great intentions, stop attending, and cancel before seeing results. The problem is not motivation — it's that nobody is checking in on them consistently and personally enough to keep them committed.",
    solution: "bigbrosai creates a daily WhatsApp touchpoint with every member — personalised workout nudges, class reminders, progress check-ins, and community moments — making members feel supported, seen, and accountable in a way that keeps them showing up.",
    metrics: [
      { value: "55%", label: "Reduction in Member Churn", icon: TrendingUp },
      { value: "82%", label: "Class Attendance Rate", icon: Users },
      { value: "2.1×", label: "Membership Renewal Rate", icon: Repeat },
      { value: "89%", label: "Member Retention at 6 Months", icon: ShieldCheck },
    ],
    useCases: [
      {
        title: "Class Booking & Reminders",
        icon: CalendarCheck,
        description: "Members book classes directly on WhatsApp and receive automated reminders that drive dramatically higher attendance rates.",
        steps: [
          "Member sends 'Book class' to studio WhatsApp number",
          "AI shows today's and tomorrow's class schedule",
          "Class selected — confirmation sent with instructor name and location",
          "60-minute reminder before class: 'Your Zumba class starts in 1 hour!'",
          "Post-class message: 'Great work today! Same time next week?'",
          "Missed class: 'We missed you! Next class is on [Day] at [Time]'",
        ],
      },
      {
        title: "Daily Workout Nudges",
        icon: Zap,
        description: "Personalised daily motivation messages — based on the member's fitness goal and programme — keep them engaged between visits.",
        steps: [
          "Member goal set at onboarding: weight loss / muscle gain / flexibility",
          "Daily message sent at preferred time (e.g., 7 AM)",
          "Monday: weekly workout tip for their goal",
          "Wednesday: mid-week motivation message",
          "Friday: weekend challenge suggestion",
          "Daily messages stop when member is already attending 5+ classes per week",
        ],
      },
      {
        title: "Membership Renewal Campaigns",
        icon: RefreshCw,
        description: "Prevent silent churn with a proactive renewal campaign that starts 30 days before expiry — with personalised offers that feel earned.",
        steps: [
          "30 days before expiry: progress summary sent ('You attended 42 classes!')",
          "20 days before: renewal offer with multi-month discount",
          "10 days before: 'Don't lose your streak!' urgency message",
          "3 days before: final offer with added benefit (1 free PT session, etc.)",
          "Expiry day: last-chance message from the studio owner personally",
          "Post-expiry win-back: 30-day and 90-day re-activation campaigns",
        ],
      },
      {
        title: "Personal Trainer Session Management",
        icon: Users,
        description: "PT clients book sessions, receive prep instructions, and get post-session homework — all through WhatsApp without any manual coordination.",
        steps: [
          "Client books PT session from available slots in chat",
          "Confirmation with trainer name and session focus sent",
          "Pre-session message: 'Eat a light meal 2 hours before'",
          "Post-session homework delivered: exercises to practice before next session",
          "Progress photo request sent weekly",
          "Monthly progress report shared with body metrics comparison",
        ],
      },
      {
        title: "Diet Plan & Supplement Promotions",
        icon: Megaphone,
        description: "Complement fitness goals with personalised nutrition tips and contextual supplement recommendations that members actually welcome.",
        steps: [
          "Weekly nutrition tip sent based on member's fitness goal",
          "New supplement or product launch announced to relevant members",
          "Buy-in-studio promotion: '20% off protein supplements this weekend'",
          "Diet plan update offered for members hitting a plateau",
          "Seasonal detox or challenge campaign sent to all active members",
          "Recipe of the week shared on Monday mornings",
        ],
      },
    ],
    quote: "Member retention went from 58% to 89% after we started bigbrosai. The daily check-ins are the difference. Members say they feel like the gym actually cares about them.",
    quoteAuthor: "Kiran Reddy",
    quoteRole: "Owner",
    quoteCompany: "IronEdge Fitness",
    relatedSlugs: ["healthcare", "beauty-retail", "events"],
  },
  {
    slug: "beauty-retail",
    label: "Beauty & Retail",
    icon: Sparkles,
    color: "#9333ea",
    heroTagline: "Fully booked. Loyal customers. Revenue on autopilot.",
    heroSubtitle: "Beauty salons and retail brands using bigbrosai cut no-shows by 73%, achieve 3.2× repeat purchase rates, and generate ₹8L+ from monthly broadcast campaigns.",
    challenge: "Beauty salons see 30% no-shows that kill daily revenue. Retail beauty brands struggle to drive repeat purchases without expensive paid ads. And both face the same problem: customers who love their products and services simply forget to come back or re-order without a timely, personal nudge.",
    solution: "bigbrosai creates a personalised WhatsApp relationship with every customer — booking reminders, exclusive loyalty rewards, new product alerts, and birthday treats — that makes customers feel like VIPs and keeps them coming back automatically.",
    metrics: [
      { value: "73%", label: "Reduction in No-shows", icon: TrendingUp },
      { value: "3.2×", label: "Repeat Purchase Rate", icon: Repeat },
      { value: "₹8L+", label: "Monthly Broadcast Revenue", icon: BarChart3 },
      { value: "4.9★", label: "Customer Satisfaction Rating", icon: Star },
    ],
    useCases: [
      {
        title: "Appointment Booking & Smart Reminders",
        icon: CalendarCheck,
        description: "Clients book appointments via WhatsApp and receive a perfectly timed reminder sequence that drives near-zero no-shows.",
        steps: [
          "Client sends 'Book appointment' to salon WhatsApp number",
          "AI shows available stylists, services, and time slots",
          "Appointment confirmed — calendar invite generated automatically",
          "24-hour reminder: service details and preparation tips ('Come with clean hair')",
          "2-hour reminder: salon address and parking instructions",
          "Post-appointment: thank you, photo if they shared, and next booking option",
        ],
      },
      {
        title: "Seasonal Offers & New Service Launches",
        icon: Megaphone,
        description: "Launch seasonal promotions and new services to your entire customer base via WhatsApp — with open rates that make email look irrelevant.",
        steps: [
          "New service or seasonal offer prepared",
          "Teaser broadcast sent 3 days before: 'Something exciting is coming...'",
          "Launch day: full details with beautiful service images and pricing",
          "Limited slots or limited-time offer creates urgency",
          "Book now button opens appointment flow directly",
          "Sold-out notification and waitlist option for high-demand offers",
        ],
      },
      {
        title: "Loyalty Points Programme",
        icon: Award,
        description: "A fully WhatsApp-native loyalty programme — no app, no card — that rewards every visit and purchase and keeps customers coming back for their next reward.",
        steps: [
          "Every appointment or purchase earns points sent via WhatsApp confirmation",
          "Balance check available anytime: 'Check my points'",
          "Milestone messages: 'You've earned a free treatment!'",
          "Points expiry reminder: 'Your 500 points expire in 30 days'",
          "VIP tier upgrade notification: 'Welcome to Gold status!'",
          "VIP benefits explained and exclusive offers sent",
        ],
      },
      {
        title: "Product Restock & New Arrival Alerts",
        icon: Bell,
        description: "For retail beauty brands, WhatsApp product alerts generate instant purchase spikes — far outperforming email or social media posts.",
        steps: [
          "New product added to inventory — broadcast prepared",
          "Segment: send only to customers who've bought from that category before",
          "Product photo, benefits, and price sent in a rich WhatsApp message",
          "Limited stock quantity mentioned to drive urgency",
          "Buy now link directly to product page included",
          "Waitlist collection for out-of-stock items",
        ],
      },
      {
        title: "Birthday & Anniversary Personalised Offers",
        icon: Star,
        description: "The most powerful retention tool in retail — a perfectly timed birthday offer that makes every customer feel remembered and special.",
        steps: [
          "Birthday and anniversary dates collected at first booking",
          "Birthday week: personalised message with exclusive offer",
          "Anniversary of first visit: 'It's been a year! Thank you for being our client'",
          "Offer link to book a special birthday treatment or buy a product",
          "No-response follow-up at day 3: 'Your birthday offer expires soon!'",
          "Post-birthday: 'Hope you had a wonderful birthday!' message",
        ],
      },
    ],
    quote: "My salon is fully booked 2 weeks in advance. And our product line sales have literally tripled since we started WhatsApp broadcasts. I cannot imagine running the business without bigbrosai.",
    quoteAuthor: "Shruti Malhotra",
    quoteRole: "Owner",
    quoteCompany: "Glow Studio",
    relatedSlugs: ["fitness", "healthcare", "ecommerce"],
  },
];

export const INDUSTRY_MAP: Record<string, Industry> = Object.fromEntries(
  INDUSTRY_LIST.map((i) => [i.slug, i])
);
